[keyshift]
192.168.5.44 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[prod_Docker]
ubsrv02 ansible_host=192.168.5.13 ansible_user=jconder44
ubsrv01 ansible_host=192.168.5.16 ansible_user=justin

[proxmox]
Balerion ansible_host=192.168.5.10 ansible_user=root
Smaug ansible_host=192.168.5.12 ansible_user=root
toothless ansible_host=192.168.5.11 ansible_user=root

[dockerProd]
prod-ubsrv-01 ansible_host=192.168.5.40
prod-ubsrv-02 ansible_host=192.168.5.43
prod-ubsrv-03 ansible_host=192.168.5.42

[dockerDev]
dev-ubsrv-01 ansible_host=192.168.5.45

[monitoring]
prod-debsrv ansible_host=192.168.5.48