
[proxmox]
Balerion ansible_host=192.168.5.10 ansible_user=root
Smaug ansible_host=192.168.5.12 ansible_user=root
toothless ansible_host=192.168.5.11 ansible_user=root

[dockerHosts]
prod-ubsrv-01 ansible_host=192.168.5.40
prod-ubsrv-02 ansible_host=192.168.5.43
prod-ubsrv-03 ansible_host=192.168.5.42
dev-ubsrv-01 ansible_host=192.168.5.45
prod-debsrv ansible_host=192.168.5.48

[dockerDev]
dev-ubsrv-01 ansible_host=192.168.5.45

[monitoring]
prod-debsrv ansible_host=192.168.5.48

[windows]
winsrv02 ansible_host=192.168.5.26

[vault]
prod-vault ansible_host=192.168.5.35


[prod_vms]
prod-vaultSrv   ansible_host=192.168.5.35
prod-ubsrv-1    ansible_host=192.168.5.40
prod-ubsrv-2    ansible_host=192.168.5.43
prod-ubsrv-3    ansible_host=192.168.5.42
prod-debsrv     ansible_host=192.168.5.48

[dev_vms]
dev-ubsrv       ansible_host=192.168.5.45

[fedora_vms]
fedsr02         ansible_host=192.168.5.27   # replace with actual IP


[containers]
pisrv01         ansible_host=192.168.5.5
pisrv02         ansible_host=192.168.5.6
omada           ansible_host=192.168.5.233
myspeed         ansible_host=192.168.5.120

[pihole]
pisrv01         ansible_host=192.168.5.5
pisrv02         ansible_host=192.168.5.6

[k3s_workers]
k8s-node01 ansible_host=192.168.5.60
k8s-node02 ansible_host=192.168.5.61
k8s-node03 ansible_host=192.168.5.62

[k3s_master]
k8s-master ansible_host=192.168.5.65

[kubernetes:children]
k3s_master
k3s_workers

[hermes]
prod-hermes-01 ansible_host=192.168.5.50

[nexusTale]
prod-nexustale ansible_host=18.222.232.1