  - name: Update and upgrade all packages
    ansible.builtin.apt:
      update_cache: true
      upgrade: dist
      cache_valid_time: 3600

  - name: Install unattended-upgrades
    ansible.builtin.apt:
      name: unattended-upgrades
      state: present

  - name: Configure unattended-upgrades
    ansible.builtin.copy:
      dest: /etc/apt/apt.conf.d/20auto-upgrades
      content: |
        APT::Periodic::Update-Package-Lists "1";
        APT::Periodic::Unattended-Upgrade "1";
