---
- name: Check if Docker is already installed
  command: docker --version
  register: docker_installed
  ignore_errors: true
  changed_when: false


- name: Install Docker dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
  when:
    - docker_installed.rc != 0 

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when:
  - docker_installed.rc != 0 

- name: Add Docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu noble stable
    state: present
  when:
    - docker_installed.rc != 0 

- name: Install Docker and Compose plugin
  apt:
    name:
      - docker-ce
      - docker-compose-plugin
    state: present
  when:
    - docker_installed.rc != 0 

- name: Add ubuntu user to docker group
  user:
    name: "{{ userName }}"
    groups: docker
    append: true
  when:
  - docker_installed.rc != 0 

- name: Create Docker service override directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'

- name: Configure Docker to expose TCP socket
  copy:
    dest: /etc/systemd/system/docker.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2375
  notify:
    - Reload systemd
    - Restart Docker

- name: Ensure Docker is enabled and started
  systemd:
    name: docker
    enabled: true
    state: started